# Generated by Django 3.2.13 on 2024-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
