# Generated by Django 5.1.3 on 2024-11-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
